name = "glbencode"
version = "1.0.0"
licences = ["Apache-2.0"]
repository = { type = "github", user = "fr0stylo", repo = "glbencode" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
